language: python

python:
  - "3.5"
  - "3.6"

# xenial and sudo workaround currently required for 3.7 on Travis,
# see: https://github.com/travis-ci/travis-ci/issues/9815
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install --no-deps -e .

script:
  - flake8 pylangacq
  - py.test -rxXs -vv --cov pylangacq pylangacq
